# Generated by Django 4.1.3 on 2022-12-18 12:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cameras',
            options={'ordering': ['-date_published', 'title'], 'verbose_name': 'Камера', 'verbose_name_plural': 'Камеры'},
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, verbose_name='Имя пользователя')),
                ('phone', models.CharField(max_length=13, verbose_name='Мобильный телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date publication')),
                ('prise', models.PositiveIntegerField(verbose_name='Цена')),
                ('products', models.ManyToManyField(to='main.cameras')),
                ('user', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
