# Generated by Django 4.1.3 on 2023-02-03 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_customuser_options_alter_customuser_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='title',
            field=models.TextField(max_length=100, verbose_name='Название'),
        ),
    ]
