# Generated by Django 4.1.3 on 2023-01-03 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(blank=True, max_length=13, verbose_name='Мобильный телефон'),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.PositiveIntegerField(blank=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.TextField(blank=True, verbose_name='Количество товара'),
        ),
        migrations.AlterField(
            model_name='order',
            name='username',
            field=models.CharField(blank=True, max_length=50, verbose_name='Имя пользователя'),
        ),
    ]
