# Generated by Django 4.1.3 on 2023-02-05 13:29

from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_feedback_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='camerasphotos',
            options={'verbose_name': 'Фото', 'verbose_name_plural': 'Все фото'},
        ),
        migrations.AlterModelOptions(
            name='feedbackphotos',
            options={'verbose_name': 'Фото', 'verbose_name_plural': 'Все фото'},
        ),
        migrations.AddField(
            model_name='feedback',
            name='images',
            field=models.ImageField(blank=True, upload_to=main.models.upload_path_autor),
        ),
        migrations.AlterField(
            model_name='camerasphotos',
            name='images',
            field=models.ImageField(blank=True, upload_to=main.models.upload_camera_photos, verbose_name='фото'),
        ),
        migrations.AlterField(
            model_name='camerasphotos',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cameras_images', to='main.cameras'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='feedbackphotos',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_images', to='main.feedback'),
        ),
    ]
