# Generated by Django 4.1.3 on 2023-02-17 15:52

from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_cameras_sold_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название галереи')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Галереи',
                'verbose_name_plural': 'Галерея',
                'ordering': ['-created'],
            },
        ),
        migrations.AlterModelOptions(
            name='feedbackphotos',
            options={'verbose_name': 'Фото отзыва', 'verbose_name_plural': 'Все фото отзывов'},
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес доставки'),
        ),
        migrations.CreateModel(
            name='GalleryPhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, upload_to=main.models.upload_path_autor, verbose_name='Фотографии')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='main.gallery')),
            ],
            options={
                'verbose_name': 'Фото галереи',
                'verbose_name_plural': 'Все фото галерей',
            },
        ),
    ]
