# Generated by Django 4.1.3 on 2023-02-19 11:38

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_gallery_alter_feedbackphotos_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='slug',
            field=models.SlugField(default=1, max_length=255, unique=True, verbose_name='URL'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='galleryphotos',
            name='images',
            field=models.ImageField(blank=True, upload_to=main.models.upload_gallery_photos, verbose_name='Фотографии'),
        ),
    ]
